//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_Employee
    {
        public int Employee_Key { get; set; }
        public Nullable<int> ID_NUMBER { get; set; }
        public string GIVEN_NAME { get; set; }
        public string FAMILY_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string CHANGE_REASON_CODE { get; set; }
        public string CHANGE_REASON_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ROW_EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> ROW_EXPIRATION_DATE { get; set; }
        public string CURRENT_ROW_INDICATOR { get; set; }
    }
}
